### PR TITLE
chore(package.json): update dependencies (Nuxt, DaisyuI, Tailwinds, D…

### PR DESCRIPTION
**Pull request by hermanno18**
**Fix issue #5**

This pull request updates the project dependencies to the latest versions, including Nuxt, DaisyUI, Tailwind CSS, Devtools, axios, postcss, eslintParser, container-queries, tailwindcss/forms, nuxt-gtag, and nuxt-headlessui-rimraf.

I used the 'npm-check-updates' package to check for updates and their dependencies. The package.json file has been updated accordingly.

Please review and merge this pull request. If there are any concerns or additional steps needed, feel free to let me know.

Thank you!

### CODE REVIEW

**Comment by jofftiquez** [comment]
Hi @hermanno18 did you use `nuxi upgrade` for this?

**Comment by hermanno18** [comment]
> Hi @hermanno18 did you use `nuxi upgrade` for this? 

Hi @jofftiquez, nope. I used a package to check updates and dependencies updates of my packages and then updated my package.json . 

Did I make this wrong ?

**Comment by jofftiquez** [comment]
> > Hi @hermanno18 did you use `nuxi upgrade` for this?
> 
> Hi @jofftiquez, nope. I used a package to check updates and dependencies updates of my packages and then updated my package.json .
> 
> Did I make this wrong ?

The correct way is to use the nuxi cli, but no worries it's basically the same. Using nuxi is just safer. I handled it already, don't worry about it. Thank you for the contribution.

**Comment by hermanno18** [comment]
> > > Hi @hermanno18 did you use `nuxi upgrade` for this?
> > 
> > Hi @jofftiquez, nope. I used a package to check updates and dependencies updates of my packages and then updated my package.json .
> > 
> > Did I make this wrong ?
> 
> The correct way is to use the nuxi cli, but no worries it's basically the same. Using nuxi is just safer. I handled it already, don't worry about it. Thank you for the contribution. 

Okay, I take note. 📝
Thanks .

**Pull request merged**
